title=Bzzzzzzzzzzzzzzzz
description=My entry for the Outline 2025 Oldschool 256b intro competition.
language=glc
date=2025-05-31
ram_model=32K RAM
preferred_rom=ROMv6
details={-----------------------------------------------------------------------+
|                                                                       |
|       Outline 2025 - Glu/WildFurs - Logo demo 256 bytes               |
|                                                                       |
+-----------------------------------------------------------------------}
gcl0x

$0500:

{ Pixeldata of outline logo
0 = Black + Black, 1 = Black + Green, 2 = Black + White
4 = Green + Black, 5 = Green + Green, 6 = Green + White
8 = White + Black, 9 = White + Green, A = White + White
Pixel data order: 0bAABBCCDD, do shiftleft2 and bitwise-and with 0b11000000 ($C0) to get the next pixel}
[def
  #$56 #$25 #$6A #$A9
  #$56 #$25 #$A0 #$0A
  #$56 #$AA #$82 #$A2
  #$A9 #$82 #$0A #$A2
  #$0A #$82 #$2A #$8A
  #$A8 #$28 #$2A #$22
  #$58 #$20 #$88 #$89
  #$5A #$82 #$02 #$A5
  #$68 #$08 #$88 #$29
  #$A0 #$A0 #$00 #$09
  #$82 #$A8 #$82 #$AA
  #$8A #$A2 #$08 #$02
  #$8A #$8A #$08 #$2A
  #$8A #$22 #$88 #$82
  #$A0 #$89 #$A8 #$8A
  #$6A #$A5 #$5A #$A9
  ] BeeData=
  
{Cheap (23 bytes) and slow way to clear screen}
$0800 Pen=
[do
  $08 Pen.
  Pen $01+ Pen=
  -$7FA3 Pen+ if&lt;0loop]  

{Put the logo on the screen and make it big!}
BeeData Logo= NextLine=
$1422 Start= Pen=           
[do
  $00 Part=						
  [do  
    [do
	  Logo, ToSplit=
	  [do
        $06 ZesKeer=
		[do
	      ToSplit $40- [if&lt;0 $00 else [$40- if&lt;0 $08 else $3F]] Pen.
	      &lt;Pen++
		  ZesKeer $01- ZesKeer= if&gt;0loop]
	    ToSplit 2&lt;&lt; $FF&amp; ToSplit=
 	    &lt;Part++ 
		Part $03&amp; if&lt;&gt;0loop]
      &lt;Logo++                      
	  Part $0F&amp; if&lt;&gt;0loop]
    &gt;Start++ Start Pen= 
	NextLine Logo=
    Part $60^ if&lt;&gt;0loop]
  NextLine $04+ NextLine= Logo=
  BeeData- $40- if&lt;&gt;0loop]
  
{Trying to emulate (kind of) a bee sound on the 4-bit audio out port and make the screen buzz too}
$0101 Screen=
[do
  $0F $2C.
  $01FD Snd=
  [do
    $06, $03&amp; Screen. $06+ Snd. 
	&gt;Snd++
    Chan $01- $03&amp; Chan= if&gt;0loop]
  loop]
  
{Yay, the compiled code is &lt;256 bytes!} 

{THAT'S ALL FOLKS!}
