at67_gigatronrombuilder_main:
    path: /gigatronrombuilder
    defaults: { _controller: at67.gigatronrombuilder.controller.main:handle }

at67_gigatronrombuilder_build:
    path: /gigatronrombuilder/build
    defaults: { _controller: at67.gigatronrombuilder.controller.main:build }

at67_gigatronrombuilder_buildMainmenu:
    path: /gigatronrombuilder/buildMainmenu
    defaults: { _controller: at67.gigatronrombuilder.controller.main:buildMainmenu }

at67_gigatronrombuilder_download:
    path: /gigatronrombuilder/download/{filename}
    defaults: { _controller: at67.gigatronrombuilder.controller.main:download }

at67_gigatronrombuilder_serve_rom:
    path: /gigatronrombuilder/serve_rom/{filename}
    defaults: { _controller: at67.gigatronrombuilder.controller.main:serveRom }

at67_gigatronrombuilder_getRomFreeSpace:
    path: /gigatronrombuilder/getRomFreeSpace
    defaults: { _controller: at67.gigatronrombuilder.controller.main:getRomFreeSpace }
