at67_gigatronshowcase_download_gt1_file:
    path: /gigatronshowcase/download/gt1/{category}/{author}/{filename}
    defaults: { _controller: at67.gigatronshowcase.controller.gt1:downloadTrackerGt1File }

at67_gigatronshowcase_download_gt1_folder:
    path: /gigatronshowcase/download/gt1/{category}/{author}/{folder}/{filename}
    defaults: { _controller: at67.gigatronshowcase.controller.gt1:downloadTrackerGt1Folder }

at67_gigatronshowcase_author_overview:
    path: /gigatronshowcase/author/{author}
    defaults: { _controller: at67.gigatronshowcase.controller.gt1:authorOverview }

at67_gigatronshowcase_author:
    path: /gigatronshowcase/author/{author}/{category}
    defaults: { _controller: at67.gigatronshowcase.controller.gt1:author }

at67_gigatronshowcase_gt1_file:
    path: /gigatronshowcase/gt1/{category}/{author}/{filename}
    defaults: { _controller: at67.gigatronshowcase.controller.gt1:gt1 }

at67_gigatronshowcase_gt1_folder:
    path: /gigatronshowcase/gt1/{category}/{author}/{folder}/{filename}
    defaults: { _controller: at67.gigatronshowcase.controller.gt1:gt1 }

at67_gigatronshowcase_download_rom:
    path: /gigatronshowcase/download/rom/{filename}
    defaults: { _controller: at67.gigatronshowcase.controller.rom:downloadTrackerRom }

at67_gigatronshowcase_rom:
    path: /gigatronshowcase/rom/{filename}
    defaults: { _controller: at67.gigatronshowcase.controller.rom:rom }

at67_gigatronshowcase_process_upload:
    path: /gigatronshowcase/submit/process
    defaults: { _controller: at67.gigatronshowcase.controller.user:processUpload }

at67_gigatronshowcase_upload_gt1:
    path: /gigatronshowcase/submit
    defaults: { _controller: at67.gigatronshowcase.controller.user:uploadForm }

at67_gigatronshowcase_upload_gt1_category:
    path: /gigatronshowcase/submit/{category}
    defaults: { _controller: at67.gigatronshowcase.controller.user:uploadForm }

at67_gigatronshowcase_process_edit_folder:
    path: /gigatronshowcase/edit/{category}/{author}/{folder}/{filename}/process
    defaults: { _controller: at67.gigatronshowcase.controller.user:processEdit }

at67_gigatronshowcase_process_edit:
    path: /gigatronshowcase/edit/{category}/{author}/{filename}/process
    defaults: { _controller: at67.gigatronshowcase.controller.user:processEdit }

at67_gigatronshowcase_edit_gt1_folder:
    path: /gigatronshowcase/edit/{category}/{author}/{folder}/{filename}
    defaults: { _controller: at67.gigatronshowcase.controller.user:editForm }

at67_gigatronshowcase_edit_gt1:
    path: /gigatronshowcase/edit/{category}/{author}/{filename}
    defaults: { _controller: at67.gigatronshowcase.controller.user:editForm }

at67_gigatronshowcase_process_delete_folder:
    path: /gigatronshowcase/delete/{category}/{author}/{folder}/{filename}/process
    defaults: { _controller: at67.gigatronshowcase.controller.user:processDelete }

at67_gigatronshowcase_process_delete:
    path: /gigatronshowcase/delete/{category}/{author}/{filename}/process
    defaults: { _controller: at67.gigatronshowcase.controller.user:processDelete }

at67_gigatronshowcase_delete_gt1_folder:
    path: /gigatronshowcase/delete/{category}/{author}/{folder}/{filename}
    defaults: { _controller: at67.gigatronshowcase.controller.user:deleteConfirm }

at67_gigatronshowcase_delete_gt1:
    path: /gigatronshowcase/delete/{category}/{author}/{filename}
    defaults: { _controller: at67.gigatronshowcase.controller.user:deleteConfirm }

at67_gigatronshowcase_main:
    path: /gigatronshowcase
    defaults: { _controller: at67.gigatronshowcase.controller.main:handle }

at67_gigatronshowcase_screenshot_save:
    path: /gigatronshowcase/screenshot/save
    defaults: { _controller: at67.gigatronshowcase.controller.main:saveScreenshot }

at67_gigatronshowcase_set_featured_screenshot:
    path: /gigatronshowcase/set_featured_screenshot
    defaults: { _controller: at67.gigatronshowcase.controller.gt1:setFeaturedScreenshot }
